export const CONFIG = {
  // Swipe
  SWIPE_THRESHOLD: 120,
  SWIPE_FLY_DISTANCE: 400,

  // Card
  CARD_WIDTH_RATIO: 0.88,
  CARD_ASPECT_RATIO: 1.5,

  // Animation
  FLIP_DURATION: 400,
  STAGGER_DELAY: 50,

  // Notes
  MAX_NOTES_ITEMS: 50,
};
